# Generated by Django 5.1 on 2024-09-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Criar_Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jogo', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_jogo', models.CharField(choices=[('3x3', '3,3'), ('5x5', '5x5')], max_length=10)),
                ('tipo_quadra', models.CharField(choices=[('Fechada', 'Fechada'), ('Aberta', 'Aberta')], max_length=10)),
                ('sexo_jogadores', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Misto', 'Misto')], max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.local')),
            ],
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_quadra', models.CharField(choices=[('Fechada', 'Fechada'), ('Aberta', 'Aberta')], max_length=10)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.local')),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel_Quadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('nome_responsavel', models.CharField(max_length=200)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quadra')),
            ],
        ),
    ]
