# Generated by Django 5.1 on 2024-09-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoops_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
